#!/usr/bin/python
"""
Created on Sep 14, 2012

Find the last Day before Today and print out all the public bullet points (PublicDayBullet).  This
could be yesterday, or it could be months ago.

@author: idcmp
"""
import sys

from pyd.tools import toolbox

if __name__ == '__main__':
    yesterday = toolbox.find_yesterday()

    if yesterday is None:
        print "Couldn't find yesterday."
        exit(0)

    public = filter(lambda entry: entry.public, yesterday.entries)

    yesterday.dump_header(sys.stdout)

    for bullet in public:
        bullet.dump(sys.stdout)
