#!/usr/bin/python
"""
Created on Apr 25, 2011

@author: idcmp
"""

import sys
import codecs

from pyd.api import naming
from pyd.tools import toolbox

if __name__ == '__main__':
    current_diary = naming.current_name()

    todos = toolbox.find_todos_in_file(current_diary)

    out = codecs.getwriter('utf-8')(sys.stdout)
    for todo in todos:
        todo.dump(out)
