#!/usr/bin/python
'''
Created on Apr 23, 2011

Add an entry to the current diary file.

@author: idcmp
'''

from pyd.api import naming
from pyd.api import editor
from pyd.api import carryforward as cf
from pyd.tools import toolbox

from codecs import open

if __name__ == '__main__':
    current_diary = naming.current_name()
    cf.perform_carryforward()
    toolbox.ensure_current_header_exists(current_diary)
    
    with open(current_diary, mode='a', encoding='utf-8') as f:
        f.write("- ")
    
    editor.launch(current_diary)
    toolbox.read_and_rewrite(current_diary)
