- introduce provisional file locking (ala ~/Diary/ww-yyyy.txt.lck)
- introduce something that can append to a day in a lock-smart way
- use the above 2 things to track git commits in a sane way
- autotrack din/dout via screensaver
- push scrum update to mobile device just before scrum
- formalize l: h: p: format
- support "dssh" which prints out the password to use
- add "* " bullet, for autodiscovered work
- add "**" for multilined autodiscovered
- autodiscover meetings from davmail
- autodiscover wiki changes
- autodiscover jira updates
- use autodiscover for git commits
- support "d" and "d+" where "d+" shows all autodiscover text
